services:
  db:
    platform: linux/x86_64
    image: percona
    container_name: Database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=HSModelaje_db
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_password

    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - laravel-exa

  main:
    container_name: Serve
    build:
      context: ./HSModelaje-backend
      dockerfile: Dockerfile
    volumes:
      - ./HSModelaje-backend:/app
      - /app/vendor  # Evita sobrescribir vendor con bind mount
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: HSModelaje_db
      DB_USERNAME: root
      DB_PASSWORD: root
      MAIL_MAILER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 465
      MAIL_USERNAME: hsmodelaje@gmail.com
      MAIL_PASSWORD: kyfkcdcbphvcvinz
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: "hsmodelaje@gmail.com"
      MAIL_FROM_NAME: "HSModelaje"
      SANCTUM_STATEFUL_DOMAINS: Serve:3000
      FRONTEND_URL: "http://localhost:3000"
      BROADCAST_DRIVER: reverb
      REVERB_ENABLED: true
      REVERB_APP_ID:  972110
      REVERB_APP_KEY: eq6doihjm8dcke8g263o
      REVERB_APP_SECRET:  tldw8swjb6rt1dawa2xp
      REVERB_HOST:  websocket-server
      REVERB_PORT:  8080
      REVERB_SCHEME:  http
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379


    networks:
      - laravel-exa
    command: >
        sh -c "while ! nc -z db 3306; do sleep 5; done &&
        [ -f .env ] || cp .env.example .env &&
        php artisan key:generate &&
        php artisan config:cache &&
        php artisan migrate:fresh --seed --force &&
        php artisan serve --host=0.0.0.0 --port=8000
        "

    # Laravel Websockets con Reverb
  websocket:
    container_name: websocket-server
    build:
      context: ./HSModelaje-backend
      dockerfile: Dockerfile
    command: php artisan reverb:start --debug
    depends_on:
      - main
    ports:
      - "8080:8080"   # 👈 Agregá esto
    networks:
      - laravel-exa

  queue:
    container_name: Queue
    build:
      context: ./HSModelaje-backend
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      - db
    networks:
      - laravel-exa

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PhpMyAdmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - laravel-exa

  mailpit:
    image: axllent/mailpit
    container_name: MailPit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel-exa

  frontend:
    container_name: frontend
    environment:
      VITE_API_URL: 'http://Serve:8000'
      VITE_WS_HOST: localhost
      VITE_WS_PORT: 8080
      VITE_PUSHER_KEY: eq6doihjm8dcke8g263o
    build:
      context: ./HSModelaje-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - laravel-exa


networks:
  laravel-exa:
    driver: bridge

volumes:
  db:
    driver: local
